# @package _global_

model:
  name: '2stage_treecrf_span_srl'
  target:
    _target_: src.models.srlmodel-treecrf-word-2o.SRLModel
  
  task:
    wprd: False
    
  decoder:
    target:
      _target_: src.models.decoders.dp.decoder-dp-word.Decoder
    threshold: 0.5
    scoring:  sIhItIp # I splits every setting. s: span marginals h/t/span: p2h(/t/span) marginals
    tree_threshold: 0.5
      
  embeddings:
    target:
      _target_: src.model.modules.embeddings.plmembedding.Embedding

    #pos
    # n_pos_embed: 100
    #char
    # n_char_embed: 50
    # n_char_out: 100
    # char_input_dropout: 0.
    # bert
    n_bert_out: 768
    n_bert_layers: 0
    mix_dropout: 0.
    finetune: True
    pooling: mean
    #word
    n_embed: 300
    ind_emb: 100

  encoder:
    target:
      _target_: src.model.module.encoder.lstm_encoder.LSTMencoder
    # emb_dropout: .33
    emb_dropout: 0.25
    emb_dropout_type: vanilla
    lstm_dropout_type: vanilla
    # lstm_dropout: .25
    lstm_dropout: 0.25
    n_lstm_hidden: 500
    n_lstm_layers: 3
    before_lstm_dropout: 0.
    bert_dropout: 0.
    # before_lstm_dropout: 0.
    bilstm: True
    # encoding: coherent
    # a_dim: 560
    # b_dim: 40
    # x_mlp: True

  foscorer:
    target:
      _target_: src.model.modules.scorer.affine.FirstOrderScorer
    span_n_out: 2
    arc_n_out: 1
    biaffine_dim: 300
    biaffine_label_dim: 500
    # arc_mlp_dropout: .25
    arc_mlp_dropout: 0.33
    # label_mlp_dropout: .25
    label_mlp_dropout: 0.
    span_dropout: 0.1
    scaling: False
    arc_init: 'zero'
    label_init: 'normal'
    # init: 'normal'
    span_affine_dim: 700
    scoring_type: 'affine'
    linear_dim: 1024
    linear_label_dim: 1024
    
  soscorer:
      target:
        _target_: src.model.modules.scorer.affine.SecondOrderScorer
      n_out: 1
      triaffine_dim: 150
      # mlp_dropout: .25
      mlp_dropout: 0.33
      scaling: False
      init: 'zero'
      decompose: False
      shared_span: False
      split: True
      # init: 'normal'
  
  mfvi:
    treemarginal: True
    structured: False
    max_iter: 3
    max_iter_decode: 3
    score_types: ['pspan','psib','pcop']
    
  span_encoder:
    # encoding: 'endpoint'
    # x_mlp: False
    # d_dim: 500
    # width_emb_dim: 20
    # coherent
    encoding: coherent
    a_dim: 560
    b_dim: 40
    x_mlp: True
  
  treecrf:
    potential_norm: True
    structure_smoothing: 1.0
  
  loss:
    lamb: 0.025
    solamb: 0
    span_lamb: 0.025
    ent_lamb: 0.
    entropy_all: False
  
  metric:
      write_result_to_file: True
      script_path: './data'
      target:
        _target_: src.models.srlmetric.SpanSRLMetric








