# https://wandb.ai

wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    project: "span-srl"
    entity: "peterv"
    job_type: "train"
    group: ""
    name: ""
    save_dir: "${work_dir}"  
    offline: True