# @package _global_

datamodule:
  # use_char: False
  use_bert: True
  # use_pos: False
  # use_word: False
  # use_emb: False
  # ext_emb_path: ""
  dataidx: 0
  bert: ''
  min_freq: 2
  fix_len: 20
  train_sampler_type: 'token'
  test_sampler_type: 'token'
  bucket: 32
  bucket_test: 32
  max_tokens: 1500
  max_tokens_test: 1500
  use_cache: True # debug: False
  use_bert_cache: True
  max_len: 10000
  max_len_test: 10000
  max_span_len: 8
  root: '.'
  distributed: False
  # for PTB only. clean (-RHS-)
  clean_word: False
  target_pad: -1
  masked_inside: False
  glove_unk: 'unk'
  sort_by_subwords: False


