# @package _global_

defaults:
  - _base

datamodule:
  target:
    _target_: src.datamodules.datasets.conllloader.CONLLDataLoader
  dataidx: 0
  context_window: 0
  train: "${root}/data/conll05/train.en.srl.conllu"
  dev: "${root}/data/conll05/dev.en.srl.conllu"
  test: "${root}/data/conll05/test.en.ood.srl.conllu"
  cache: "${root}/data/conll05/conll05-brown.pickle"
  cache_bert: "${root}/data/conll05/conll05-brown.cache_bert"
  # ext_emb_path: "${root}/data/ptb/glove.6B.100d.txt"
  use_bert: True
  use_cache: True # debug: False
  use_bert_cache: True
  clean_word: False
  bert: 'bert-large-cased'
  name: 'conll05-brown'
  batch_size: 16
  golden_predicate: False
  masked_inside: False
  # max_len: 100

# model:
#   metric:
#     target:
#       _target_: src.model.metric.NERMetric
#     write_result_to_file: True





